### PR TITLE
[DROP] `getPagesTSconfig`

### PR DESCRIPTION
**Pull request by xerc**
https://api.typo3.org/12.4/classes/TYPO3-CMS-Frontend-Controller-TypoScriptFrontendController.html#method_getPagesTSconfig

### CODE REVIEW

**Comment by xerc** [comment]
@Bunnyfield the TSConfig is loaded with this change in any circumstance
at `12.4` fct. `$GLOBALS['TSFE']->getPagesTSconfig()` does not load fully
& `11.5` internaly only uses `BackendUtility::getPagesTSconfig` anyway

only @ https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/frontend/Classes/Typolink/DatabaseRecordLinkBuilder.php#L35
```
git clone git@github.com:TYPO3/typo3.git /tmp/typo3dump && cd $_ && git checkout 11.5
grep -rH 'getPagesTSconfig' typo3/sysext/*/Classes
```

**Comment by xerc** [comment]
i saw your FIX for these old versions but this changed - even `10.4` uses the "old" variant only once (same file)
may your please re-check `12.4` that the return of `$GLOBALS['TSFE']->getPagesTSconfig()` contains the [TSC
](https://docs.typo3.org/p/gridelementsteam/gridelements/main/en-us/Chapters/Tsconfig/Index.html#tx-gridelements-setup)
at mine `12.4.23` the only `gridelements` part is .. at the end
```
  ["templates."]=>
  array(1) {
    ["typo3/cms-backend."]=>
    array(1) {
      [1693847017]=>
      string(66) "gridelementsteam/gridelements:Resources/Private/Backend/PageModule"
    }
  }
}
```
@ vendor/gridelementsteam/gridelements/Classes/Backend/LayoutSetup.php
```patch
     protected function loadLayoutSetup(int $pageId): void
     {
+var_dump($GLOBALS['TSFE']->getPagesTSconfig());die;
```

**Comment by xerc** [comment]
look like relative paths are the probl. with `TSFE`
```@import 'sources/typoconfig/'``` works fine
```@import 'typoconfig/'``` does not load files

but both work/load correctly with `BU::`

**Comment by Bunnyfield** [comment]
This might depend on the way you defined your CE-backend-layouts for your Gridelements.

If you did it with PageTSconfig and not based on database records, the setup will most likely show a similar structure

image

This can be achieved by either writing the TSconfig into the database field of a page record or by including it from within a sitepackage extension., In both cases it will provide crucial information about Gridelements structures in the frontend.

**Comment by xerc** [comment]
> look like relative paths are the probl. with `TSFE` `@import 'sources/typoconfig/'` works fine `@import 'typoconfig/'` does not load files - but both work/load correctly with `BU::`

it is definitly the broken relative import within `$GLOBALS['TSFE']->getPagesTSconfig()` (checked other 2 prj.)

**Comment by Bunnyfield** [comment]
So the question is, why the core itself recommends a completely different approach
```

    /********************************************
     *
     * Various external API functions - for use in plugins etc.
     *
     *******************************************/
    /**
     * Returns the pages TSconfig array based on the current ->rootLine
     *
     * @deprecated since TYPO3 v12, will be removed in v13. Frontend should typically not depend on Backend TsConfig.
     *             If really needed, use PageTsConfigFactory, see usage in DatabaseRecordLinkBuilder.
     *             Remove together with class PageTsConfig.
     */
```
which we actually implemented in the early access version of Gridelements 13?

**Comment by xerc** [comment]
> So the question is, why the core itself recommends a completely different approach

link please

**Comment by Bunnyfield** [comment]
It's mentioned in the comment of the method itself:

```
    /********************************************
     *
     * Various external API functions - for use in plugins etc.
     *
     *******************************************/
    /**
     * Returns the pages TSconfig array based on the current ->rootLine
     *
     * @deprecated since TYPO3 v12, will be removed in v13. Frontend should typically not depend on Backend TsConfig.
     *             If really needed, use PageTsConfigFactory, see usage in DatabaseRecordLinkBuilder.
     *             Remove together with class PageTsConfig.
     */
```

**Comment by Bunnyfield** [comment]
https://github.com/TYPO3/typo3/blob/ae0cb077007dfa8f28a368c767532624b0d3cf78/typo3/sysext/frontend/Classes/Typolink/DatabaseRecordLinkBuilder.php#L119

**Comment by Bunnyfield** [comment]
Fun fact: Although the method itself says "we can't use BackendUtility", the PageTSconfigFactory it makes use of says
```
 *
 * @internal Internal for now until API stabilized. Use BackendUtility::getPagesTSconfig().
 */
```
Still, to be on the safe side I would go for a separation of frontend and backend context.

**Comment by xerc** [comment]
sure ; so.. `->getPagesTSconfig` does not resolve relative TSC paths at `@import grid/` -only- with `@import ./grid/`
-but- `::getPagesTSconfig()` does it correctly -and- the TypoScript parser also understands 'relative' without probl.

**Comment by xerc** [comment]
> we do it like the core does and make use of BE::getPagesTSconfig() in the frontend until that stops working - again?

na.. will patch it on my side

```patch
--- cms-core/Classes/TypoScript/Parser/TypoScriptParser.bak	2024-12-09 18:38:43.820530030 +0100
+++ cms-core/Classes/TypoScript/Parser/TypoScriptParser.php	2024-12-09 18:39:35.026532108 +0100
@@ -859,7 +859,7 @@
                 $filename = $parts[$i];
                 $tsContentsTillNextInclude = $parts[$i + 1];
                 // Resolve a possible relative paths if a parent file is given
-                if ($parentFilenameOrPath !== '' && $filename[0] === '.') {
+                if ($parentFilenameOrPath !== '' && ($filename[0] === '.' || $filename[-1] === '/')) {#! XERC
                     $filename = PathUtility::getAbsolutePathOfRelativeReferencedFileOrPath($parentFilenameOrPath, $filename);
                 }
                 $newString .= self::importExternalTypoScriptFile($filename, $cycleCounter, $returnFiles, $includedFiles);
```

TSconfig seems not the best location for FE config  ;)

**Pull request closed without merging**
